name: transforna
channels:
  - pytorch
  - bioconda
  - conda-forge
dependencies:
  - anndata==0.8.0
  - dill==0.3.6
  - hydra-core==1.3.0
  - imbalanced-learn==0.9.1
  - matplotlib==3.5.3
  - numpy==1.22.3
  - omegaconf==2.2.2
  - pandas==1.5.2
  - plotly==5.10.0
  - PyYAML==6.0
  - rich==12.6.0
  - viennarna=2.5.0=py39h98c8e45_0
  - scanpy==1.9.1
  - scikit-learn==1.2.0
  - skorch==0.12.1
  - pytorch=1.10.1=py3.9_cuda11.3_cudnn8.2.0_0
  - tensorboard==2.11.2
  - Levenshtein==0.21.0