defaults: 
  - model: transforna
  - inference_settings: default
  - override hydra/job_logging: disaabled

task: tcga # tcga,sncrna or premirna or custom (for a custom dataset)


train_config:
  _target_: train_model_configs.${task}.GeneEmbeddTrainConfig

model_config:
  _target_: train_model_configs.${task}.GeneEmbeddModelConfig

#train settings
model_name: seq #seq, seq-seq, seq-struct, seq-reverse, or baseline
trained_on: full #full or id
path_to_id_models: /nfs/home/yat_ldap/VS_Projects/TransfoRNA-Framework/models/tcga/ #will be used if trained_on is full
inference: False   # True or False
#if inference is true, should the logits be logged?
log_logits: False


train_split: True  # True or False
valid_size: 0.15   # 0 < valid_size < 1

#CV
cross_val: True    # True or False
num_replicates: 1  # Integer, num_replicates > 1

#seed
seed: 1            # Integer
device_number: 1   # Integer, select GPU


#logging sequence embeddings + metrics to tensorboard
log_embedds: True  # True or False
tensorboard: False  # True or False

#disable hydra output
hydra:  
  run:  
    dir: ./outputs/${now:%Y-%m-%d}/${model_name}
  #./outputs2/
  searchpath: 
   - file:///nfs/home/yat_ldap/VS_Projects/TransfoRNA-Framework/conf
#  output_subdir: null  





