defaults: 
  - model: transforna
  - inference_settings: default
  - override hydra/job_logging: disabled

task: tcga # tcga,sncrna or premirna or custom (for a custom dataset)


train_config:
  _target_: train_model_configs.${task}.GeneEmbeddTrainConfig

model_config:
  _target_: train_model_configs.${task}.GeneEmbeddModelConfig

#train settings
model_name: seq #seq, seq-seq, seq-struct, seq-reverse, or baseline
trained_on: full #full(production, more coverage) or id (for test/eval purposes)
path_to_models: /media/ftp_share/hbdx/analysis/transforna_LC/ #edit path to point to models/tcga/ directory: will be used if trained_on is full
inference: True   # Should TransfoRNA be used for inference or train? True or False
#if inference is true, should the logits be logged?
log_logits: False


train_split: True  # True or False
valid_size: 0.15   # 0 < valid_size < 1

#CV
cross_val: True    # True or False
num_replicates: 1  # Integer, num_replicates for cross-validation

#seed
seed: 1            # Integer
device_number: 1   # Integer, select GPU


#logging sequence embeddings + metrics to tensorboard
log_embedds: True  # True or False
tensorboard: False  # True or False

#disable hydra output
hydra:  
  run:  
    dir: /media/ftp_share/hbdx/analysis/transforna_LC/TransfoRNA_FULL/sub_class/${model_name} #./outputs/${now:%Y-%m-%d}/${model_name} # 
  searchpath: 
   - file:///nfs/home/jje_ldap/TransfoRNA/conf/train_model_configs/
#  output_subdir: null  #uncomment to disable hydra output





